"""Machine-readable error codes for provenance event taxonomy."""

LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_PARSE_FAILURE = "LLM_PARSE_FAILURE"
LLM_VALIDATION_FAILURE = "LLM_VALIDATION_FAILURE"
LLM_UNEXPECTED_ERROR = "LLM_UNEXPECTED_ERROR"
LLM_RETRIES_EXHAUSTED = "LLM_RETRIES_EXHAUSTED"
OLS_API_ERROR = "OLS_API_ERROR"
